#!/bin/sh

# Translate standard language codes to Adobe language codes
if   [ "$LANGCODE" = "ca" ];      then ADOBE_LANG="esp" # Catalan
elif [ "$LANGCODE" = "da" ];      then ADOBE_LANG="dan" # Danish
elif [ "$LANGCODE" = "de" ];      then ADOBE_LANG="deu" # German
elif [ "$LANGCODE" = "es" ];      then ADOBE_LANG="esp" # Spanish
elif [ "$LANGCODE" = "eu" ];      then ADOBE_LANG="esp" # Basque
elif [ "$LANGCODE" = "fi" ];      then ADOBE_LANG="suo" # Finnish
elif [ "$LANGCODE" = "fr" ];      then ADOBE_LANG="fra" # French
elif [ "$LANGCODE" = "gl" ];      then ADOBE_LANG="esp" # Galician
elif [ "$LANGCODE" = "it" ];      then ADOBE_LANG="ita" # Italian
elif [ "$LANGCODE" = "ja" ];      then ADOBE_LANG="jpn" # Japanese
elif [ "$LANGCODE" = "ko" ];      then ADOBE_LANG="kor" # Korean
elif [ "$LANGCODE" = "nl" ];      then ADOBE_LANG="nld" # Dutch
elif [ "$LANGCODE" = "no" ];      then ADOBE_LANG="nor" # Norwegian
elif [ "$LANGCODE" = "pt" ];      then ADOBE_LANG="ptb" # Portuguese
elif [ "$LANGCODE" = "sv" ];      then ADOBE_LANG="sve" # Swedish
elif [ "$LOCALECODE" = "zh_CN" ]; then ADOBE_LANG="chs" # Chinese Simplified
elif [ "$LOCALECODE" = "zh_TW" ]; then ADOBE_LANG="cht" # Chinese Traditional
elif [ "$LANGCODE" = "zh" ];      then ADOBE_LANG="chs" # Chinese
else                                   ADOBE_LANG="enu"
fi

echo "adobereader-$ADOBE_LANG" >> "$1"

