# -*- coding: UTF-8 -*-

# This file was automatically generated from:
#   d-i/source/console-setup/Keyboard/MyKeyboardNames.pl
# Instead of editing this file, it is better to edit the original and
# regenerate this.

models = {
    'A4Tech KB-21': 'a4techKB21',
    'A4Tech KBS-8': 'a4techKBS8',
    'A4Tech Wireless Desktop RFKB-23': 'a4_rfkb23',
    'ACPI Standard': 'acpi',
    'Acer AirKey V': 'airkey',
    'Acer C300': 'acer_c300',
    'Acer Ferrari 4000': 'acer_ferrari4k',
    'Acer Laptop': 'acer_laptop',
    'Advance Scorpius KI': 'scorpius',
    'Amiga': 'amiga',
    'Apple': 'apple',
    'Apple Laptop': 'apple_laptop',
    'Asus Laptop': 'asus_laptop',
    'Atari TT': 'ataritt',
    'Azona RF2300 wireless Internet Keyboard': 'azonaRF2300',
    'BTC 5090': 'btc5090',
    'BTC 5113RF Multimedia': 'btc5113rf',
    'BTC 5126T': 'btc5126t',
    'BTC 6301URF': 'btc6301urf',
    'BTC 9000': 'btc9000',
    'BTC 9000A': 'btc9000a',
    'BTC 9001AH': 'btc9001ah',
    'BTC 9019U': 'btc9019u',
    'BTC 9116U Mini Wireless Internet and Gaming': 'btc9116u',
    'BenQ X-Touch': 'benqx',
    'BenQ X-Touch 730': 'benqx730',
    'BenQ X-Touch 800': 'benqx800',
    'Brazilian ABNT2': 'abnt2',
    'Brother Internet Keyboard': 'brother',
    'Cherry Blue Line CyBo@rd': 'cherryblue',
    'Cherry Blue Line CyBo@rd (alternate option)': 'cherrybluea',
    'Cherry CyBo@rd USB-Hub': 'cherrycyboard',
    'Cherry CyMotion Expert': 'cherrycmexpert',
    'Cherry CyMotion Master Linux': 'cymotionlinux',
    'Cherry CyMotion Master XPress': 'cherryblueb',
    'Chicony Internet Keyboard': 'chicony',
    'Chicony KB-9885': 'chicony9885',
    'Chicony KU-0108': 'chicony0108',
    'Chicony KU-0420': 'chicony0420',
    'Classmate PC': 'classmate',
    'Compaq Easy Access Keyboard': 'compaqeak8',
    'Compaq Internet Keyboard (13 keys)': 'compaqik13',
    'Compaq Internet Keyboard (18 keys)': 'compaqik18',
    'Compaq Internet Keyboard (7 keys)': 'compaqik7',
    'Compaq iPaq Keyboard': 'ipaq',
    'DTK2000': 'dtk2000',
    'Dell': 'dell',
    'Dell 101-key PC': 'dell101',
    'Dell Laptop/notebook Inspiron 6xxx/8xxx': 'inspiron',
    'Dell Laptop/notebook Precision M series': 'precision_m',
    'Dell Latitude series laptop': 'latitude',
    'Dell Precision M65': 'dellm65',
    'Dell SK-8125': 'dellsk8125',
    'Dell SK-8135': 'dellsk8135',
    'Dell USB Multimedia Keyboard': 'dellusbmm',
    'Dexxa Wireless Desktop Keyboard': 'dexxa',
    'Diamond 9801 / 9802 series': 'diamond',
    'Do not configure keyboard; keep kernel keymap': 'SKIP',
    'Ennyah DKB-1008': 'ennyah_dkb1008',
    'Evdev-managed keyboard': 'evdev',
    'Everex STEPnote': 'everex',
    'FL90': 'compalfl90',
    'Fujitsu-Siemens Computers AMILO laptop': 'fscaa1667g',
    'Generic 101-key PC': 'pc101',
    'Generic 102-key (Intl) PC': 'pc102',
    'Generic 104-key PC': 'pc104',
    'Generic 105-key (Intl) PC': 'pc105',
    'Genius Comfy KB-12e': 'geniuscomfy',
    'Genius Comfy KB-16M / Genius MM Keyboard KWD-910': 'genius',
    'Genius Comfy KB-21e-Scroll': 'geniuscomfy2',
    'Genius KB-19e NB': 'geniuskb19e',
    'Gyration': 'gyration',
    'Happy Hacking Keyboard': 'hhk',
    'Happy Hacking Keyboard for Mac': 'macintosh_hhk',
    'Hewlett-Packard Internet Keyboard': 'hpi6',
    'Hewlett-Packard Omnibook 500 FA': 'hp500fa',
    'Hewlett-Packard Omnibook 5xx': 'hp5xx',
    'Hewlett-Packard Omnibook 6000/6100': 'hp6000',
    'Hewlett-Packard Omnibook XE3 GC': 'hpxe3gc',
    'Hewlett-Packard Omnibook XE3 GF': 'hpxe3gf',
    'Hewlett-Packard Omnibook XT1000': 'hpxt1000',
    'Hewlett-Packard Pavilion ZT11xx': 'hpzt11xx',
    'Hewlett-Packard Pavilion dv5': 'hpdv5',
    'Hewlett-Packard SK-250x Multimedia Keyboard': 'hp250x',
    'Hewlett-Packard nx9020': 'hpnx9020',
    'Honeywell Euroboard': 'honeywell_euroboard',
    'IBM Rapid Access': 'rapidaccess',
    'IBM Rapid Access II': 'rapidaccess2',
    'IBM Space Saver': 'ibm_spacesaver',
    'IBM ThinkPad 560Z/600/600E/A22E': 'thinkpad',
    'IBM ThinkPad 560Z/600/600E/A22E, Intl': 'thinkpadintl',
    'IBM ThinkPad R60/T60/R61/T61': 'thinkpad60',
    'IBM ThinkPad Z60m/Z60t/Z61m/Z61t': 'thinkpadz60',
    'Japanese 106-key': 'jp106',
    'Keytronic FlexPro': 'flexpro',
    'Korean 106-key': 'kr106',
    'Laptop/notebook Compaq (eg. Armada) Laptop Keyboard': 'armada',
    'Laptop/notebook Compaq (eg. Presario) Internet Keyboard': 'presario',
    'Laptop/notebook eMachines m68xx': 'emachines',
    'Logitech Access Keyboard': 'logiaccess',
    'Logitech Cordless Desktop': 'logicd',
    'Logitech Cordless Desktop (alternate option)': 'logicda',
    'Logitech Cordless Desktop EX110': 'logiex110',
    'Logitech Cordless Desktop LX-300': 'logiclx300',
    'Logitech Cordless Desktop Navigator': 'logicdn',
    'Logitech Cordless Desktop Optical': 'logicd_opt',
    'Logitech Cordless Desktop Pro (alternate option2)': 'logicdpa2',
    'Logitech Cordless Desktop iTouch': 'logicd_it',
    'Logitech Cordless Freedom/Desktop Navigator': 'logicfn',
    'Logitech G15 extra keys via G15daemon': 'logitech_g15',
    'Logitech Generic Keyboard': 'logitech_base',
    'Logitech Internet 350 Keyboard': 'logii350',
    'Logitech Internet Keyboard': 'logiik',
    'Logitech Internet Navigator Keyboard': 'logicink',
    'Logitech Media Elite Keyboard': 'logimel',
    'Logitech Ultra-X Cordless Media Desktop Keyboard': 'logiultraxc',
    'Logitech Ultra-X Keyboard': 'logiultrax',
    'Logitech diNovo Edge Keyboard': 'logidinovoedge',
    'Logitech diNovo Keyboard': 'logidinovo',
    'Logitech iTouch': 'itouch',
    'Logitech iTouch Cordless Keyboard (model Y-RB6)': 'logiitc',
    'Logitech iTouch Internet Navigator Keyboard SE': 'logiinkse',
    'Logitech iTouch Internet Navigator Keyboard SE (USB)': 'logiinkseusb',
    'MacBook/MacBook Pro': 'macbook78',
    'MacBook/MacBook Pro (Intl)': 'macbook79',
    'Macintosh': 'macintosh',
    'Macintosh Old': 'macintosh_old',
    'Memorex MX1998': 'mx1998',
    'Memorex MX2500 EZ-Access Keyboard': 'mx2500',
    'Memorex MX2750': 'mx2750',
    'Microsoft Comfort Curve Keyboard 2000': 'microsoftccurve2k',
    'Microsoft Internet Keyboard': 'microsoftinet',
    'Microsoft Internet Keyboard Pro, Swedish': 'microsoftprose',
    'Microsoft Natural': 'microsoft',
    'Microsoft Natural Keyboard Elite': 'microsoftelite',
    'Microsoft Natural Keyboard Pro / Microsoft Internet Keyboard Pro': 'microsoftpro',
    'Microsoft Natural Keyboard Pro OEM': 'microsoftprooem',
    'Microsoft Natural Keyboard Pro USB / Microsoft Internet Keyboard Pro': 'microsoftprousb',
    'Microsoft Natural Wireless Ergonomic Keyboard 7000': 'microsoft7000',
    'Microsoft Office Keyboard': 'microsoftoffice',
    'Microsoft Wireless Multimedia Keyboard 1.0A': 'microsoftmult',
    'Northgate OmniKey 101': 'omnikey101',
    'OLPC': 'olpc',
    'Ortek MCK-800 MM/Internet keyboard': 'oretec',
    'PC-98xx Series': 'pc98',
    'Propeller Voyager (KTEZ-1000)': 'propeller',
    'QTronix Scorpius 98N+': 'qtronix',
    'SILVERCREST Multimedia Wireless Keyboard': 'silvercrest',
    'SK-1300': 'sk1300',
    'SK-2500': 'sk2500',
    'SK-6200': 'sk6200',
    'SK-7100': 'sk7100',
    'SVEN Ergonomic 2500': 'sven',
    'SVEN Slim 303': 'sven303',
    'Samsung SDM 4500P': 'samsung4500',
    'Samsung SDM 4510P': 'samsung4510',
    'Sun Type 4': 'sun4',
    'Sun Type 5': 'sun5',
    'Sun Type 5/6': 'sun6',
    'Super Power Multimedia Keyboard': 'sp_inet',
    'Symplon PaceBook (tablet PC)': 'symplon',
    'Targa Visionary 811': 'targa_v811',
    'Toshiba Satellite S3000': 'toshiba_s3000',
    'Trust Direct Access Keyboard': 'trustda',
    'Trust Wireless Keyboard Classic': 'trust',
    'Unitek KB-1925': 'unitekkb1925',
    'ViewSonic KU-306 Internet Keyboard': 'vsonku306',
    'Winbook Model XP5': 'winbook',
    'Yahoo! Internet Keyboard': 'yahoo',
}

models_rev = {}
models_rev.update(((v, k) for (k, v) in models.iteritems()))

layouts = {
    'Afghanistan': 'af',
    'Albania': 'al',
    'Andorra': 'ad',
    'Arabic': 'ara',
    'Armenia': 'am',
    'Azerbaijan': 'az',
    'Bangladesh': 'bd',
    'Belarus': 'by',
    'Belgium': 'be',
    'Bhutan': 'bt',
    'Bosnia and Herzegovina': 'ba',
    'Braille': 'braille',
    'Brazil': 'br',
    'Bulgaria': 'bg',
    'Cambodia': 'kh',
    'Canada': 'ca',
    'China': 'cn',
    'Congo, Democratic Republic of the': 'cd',
    'Croatia': 'hr',
    'Czechia': 'cz',
    'Denmark': 'dk',
    'Esperanto': 'epo',
    'Estonia': 'ee',
    'Ethiopia': 'et',
    'Faroe Islands': 'fo',
    'Finland': 'fi',
    'France': 'fr',
    'Georgia': 'ge',
    'Germany': 'de',
    'Ghana': 'gh',
    'Greece': 'gr',
    'Guinea': 'gn',
    'Hungary': 'hu',
    'Iceland': 'is',
    'India': 'in',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Ireland': 'ie',
    'Israel': 'il',
    'Italy': 'it',
    'Japan': 'jp',
    'Japan (PC-98xx Series)': 'nec_vndr/jp',
    'Kazakhstan': 'kz',
    'Korea, Republic of': 'kr',
    'Kyrgyzstan': 'kg',
    'Laos': 'la',
    'Latin American': 'latam',
    'Latvia': 'lv',
    'Lithuania': 'lt',
    'Macedonia': 'mk',
    'Maldives': 'mv',
    'Malta': 'mt',
    'Maori': 'mao',
    'Mongolia': 'mn',
    'Montenegro': 'me',
    'Morocco': 'ma',
    'Myanmar': 'mm',
    'Nepal': 'np',
    'Netherlands': 'nl',
    'Nigeria': 'ng',
    'Norway': 'no',
    'Pakistan': 'pk',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Romania': 'ro',
    'Russia': 'ru',
    'Serbia': 'rs',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'South Africa': 'za',
    'Spain': 'es',
    'Sri Lanka': 'lk',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Syria': 'sy',
    'Tajikistan': 'tj',
    'Thailand': 'th',
    'Turkey': 'tr',
    'USA': 'us',
    'Ukraine': 'ua',
    'United Kingdom': 'gb',
    'Uzbekistan': 'uz',
    'Vietnam': 'vn',
}

layouts_rev = {}
layouts_rev.update(((v, k) for (k, v) in layouts.iteritems()))

variants = {
    'af': {
        'Afghanistan': '',
        'Afghanistan - OLPC Dari': 'olpc-fa',
        'Afghanistan - OLPC Pashto': 'olpc-ps',
        'Afghanistan - OLPC Southern Uzbek': 'olpc-uz',
        'Afghanistan - Pashto': 'ps',
        'Afghanistan - Southern Uzbek': 'uz',
    },
    'am': {
        'Armenia': '',
        'Armenia - Alternative Eastern': 'eastern-alt',
        'Armenia - Alternative Phonetic': 'phonetic-alt',
        'Armenia - Eastern': 'eastern',
        'Armenia - Phonetic': 'phonetic',
        'Armenia - Western': 'western',
    },
    'ara': {
        'Arabic': '',
        'Arabic - Buckwalter': 'buckwalter',
        'Arabic - azerty': 'azerty',
        'Arabic - azerty/digits': 'azerty_digits',
        'Arabic - digits': 'digits',
        'Arabic - qwerty': 'qwerty',
        'Arabic - qwerty/digits': 'qwerty_digits',
    },
    'az': {
        'Azerbaijan': '',
        'Azerbaijan - Cyrillic': 'cyrillic',
    },
    'ba': {
        'Bosnia and Herzegovina': '',
        'Bosnia and Herzegovina - US keyboard with Bosnian digraphs': 'unicodeus',
        'Bosnia and Herzegovina - US keyboard with Bosnian letters': 'us',
        'Bosnia and Herzegovina - Use Bosnian digraphs': 'unicode',
        'Bosnia and Herzegovina - Use guillemets for quotes': 'alternatequotes',
    },
    'bd': {
        'Bangladesh': '',
        'Bangladesh - Probhat': 'probhat',
    },
    'be': {
        'Belgium': '',
        'Belgium - Alternative': 'oss',
        'Belgium - Alternative, Sun dead keys': 'oss_sundeadkeys',
        'Belgium - Alternative, latin-9 only': 'oss_latin9',
        'Belgium - Eliminate dead keys': 'nodeadkeys',
        'Belgium - ISO Alternate': 'iso-alternate',
        'Belgium - Sun dead keys': 'sundeadkeys',
        'Belgium - Wang model 724 azerty': 'wang',
    },
    'bg': {
        'Bulgaria': '',
        'Bulgaria - Standard Phonetic': 'bas_phonetic',
        'Bulgaria - Traditional Phonetic': 'phonetic',
    },
    'br': {
        'Brazil': '',
        'Brazil - Dvorak': 'dvorak',
        'Brazil - Eliminate dead keys': 'nodeadkeys',
        'Brazil - Nativo': 'nativo',
        'Brazil - Nativo for Esperanto': 'nativo-epo',
        'Brazil - Nativo for USA keyboards': 'nativo-us',
    },
    'braille': {
        'Braille': '',
        'Braille - Left hand': 'left_hand',
        'Braille - Right hand': 'right_hand',
    },
    'by': {
        'Belarus': '',
        'Belarus - Latin': 'latin',
        'Belarus - Winkeys': 'winkeys',
    },
    'ca': {
        'Canada': '',
        'Canada - English': 'eng',
        'Canada - French (legacy)': 'fr-legacy',
        'Canada - French Dvorak': 'fr-dvorak',
        'Canada - Inuktitut': 'ike',
        'Canada - Ktunaxa': 'kut',
        'Canada - Multilingual': 'multix',
        'Canada - Multilingual, first part': 'multi',
        'Canada - Multilingual, second part': 'multi-2gr',
        'Canada - Secwepemctsin': 'shs',
    },
    'ch': {
        'Switzerland': '',
        'Switzerland - French': 'fr',
        'Switzerland - French (Macintosh)': 'fr_mac',
        'Switzerland - French, Sun dead keys': 'fr_sundeadkeys',
        'Switzerland - French, eliminate dead keys': 'fr_nodeadkeys',
        'Switzerland - German (Macintosh)': 'de_mac',
        'Switzerland - German, Sun dead keys': 'de_sundeadkeys',
        'Switzerland - German, eliminate dead keys': 'de_nodeadkeys',
    },
    'cn': {
        'China': '',
        'China - Tibetan': 'tib',
        'China - Tibetan (with ASCII numerals)': 'tib_asciinum',
    },
    'cz': {
        'Czechia': '',
        'Czechia - UCW layout (accented letters only)': 'ucw',
        'Czechia - With <\|> key': 'bksl',
        'Czechia - qwerty': 'qwerty',
        'Czechia - qwerty, extended Backslash': 'qwerty_bksl',
    },
    'de': {
        'Germany': '',
        'Germany - Dead acute': 'deadacute',
        'Germany - Dead grave acute': 'deadgraveacute',
        'Germany - Dvorak': 'dvorak',
        'Germany - Eliminate dead keys': 'nodeadkeys',
        'Germany - Lower Sorbian': 'dsb',
        'Germany - Lower Sorbian (qwertz)': 'dsb_qwertz',
        'Germany - Macintosh': 'mac',
        'Germany - Macintosh, eliminate dead keys': 'mac_nodeadkeys',
        'Germany - Neo 2': 'neo',
        'Germany - Romanian keyboard with German letters': 'ro',
        'Germany - Romanian keyboard with German letters, eliminate dead keys': 'ro_nodeadkeys',
        'Germany - Sun dead keys': 'sundeadkeys',
        'Germany - qwerty': 'qwerty',
    },
    'dk': {
        'Denmark': '',
        'Denmark - Dvorak': 'dvorak',
        'Denmark - Eliminate dead keys': 'nodeadkeys',
        'Denmark - Macintosh': 'mac',
        'Denmark - Macintosh, eliminate dead keys': 'mac_nodeadkeys',
    },
    'ee': {
        'Estonia': '',
        'Estonia - Dvorak': 'dvorak',
        'Estonia - Eliminate dead keys': 'nodeadkeys',
        'Estonia - US keyboard with Estonian letters': 'us',
    },
    'epo': {
        'Esperanto': '',
        'Esperanto - displaced semicolon and quote (obsolete)': 'legacy',
    },
    'es': {
        'Spain': '',
        'Spain - Asturian variant with bottom-dot H and bottom-dot L': 'ast',
        'Spain - Catalan variant with middle-dot L': 'cat',
        'Spain - Dvorak': 'dvorak',
        'Spain - Eliminate dead keys': 'nodeadkeys',
        'Spain - Include dead tilde': 'deadtilde',
        'Spain - Macintosh': 'mac',
        'Spain - Sun dead keys': 'sundeadkeys',
    },
    'fi': {
        'Finland': '',
        'Finland - Classic': 'classic',
        'Finland - Eliminate dead keys': 'nodeadkeys',
        'Finland - Macintosh': 'mac',
        'Finland - Northern Saami': 'smi',
    },
    'fo': {
        'Faroe Islands': '',
        'Faroe Islands - Eliminate dead keys': 'nodeadkeys',
    },
    'fr': {
        'France': '',
        'France - (Legacy) Alternative': 'latin9',
        'France - (Legacy) Alternative, Sun dead keys': 'latin9_sundeadkeys',
        'France - (Legacy) Alternative, eliminate dead keys': 'latin9_nodeadkeys',
        'France - Alternative': 'oss',
        'France - Alternative, Sun dead keys': 'oss_sundeadkeys',
        'France - Alternative, eliminate dead keys': 'oss_nodeadkeys',
        'France - Alternative, latin-9 only': 'oss_latin9',
        'France - Bepo, ergonomic, Dvorak way': 'bepo',
        'France - Bepo, ergonomic, Dvorak way, latin-9 only': 'bepo_latin9',
        'France - Breton': 'bre',
        'France - Dvorak': 'dvorak',
        'France - Eliminate dead keys': 'nodeadkeys',
        'France - Georgian AZERTY Tskapo': 'geo',
        'France - Macintosh': 'mac',
        'France - Sun dead keys': 'sundeadkeys',
    },
    'gb': {
        'United Kingdom': '',
        'United Kingdom - Colemak': 'colemak',
        'United Kingdom - Dvorak': 'dvorak',
        'United Kingdom - Dvorak (UK Punctuation)': 'dvorakukp',
        'United Kingdom - International (with dead keys)': 'intl',
        'United Kingdom - Macintosh': 'mac',
    },
    'ge': {
        'Georgia': '',
        'Georgia - Ergonomic': 'ergonomic',
        'Georgia - MESS': 'mess',
        'Georgia - Ossetian': 'os',
        'Georgia - Russian': 'ru',
    },
    'gh': {
        'Ghana': '',
        'Ghana - Akan': 'akan',
        'Ghana - Ewe': 'ewe',
        'Ghana - Fula': 'fula',
        'Ghana - Ga': 'ga',
        'Ghana - Hausa': 'hausa',
        'Ghana - Multilingual': 'generic',
    },
    'gr': {
        'Greece': '',
        'Greece - Eliminate dead keys': 'nodeadkeys',
        'Greece - Extended': 'extended',
        'Greece - Polytonic': 'polytonic',
        'Greece - Simple': 'simple',
    },
    'hr': {
        'Croatia': '',
        'Croatia - US keyboard with Croatian digraphs': 'unicodeus',
        'Croatia - US keyboard with Croatian letters': 'us',
        'Croatia - Use Croatian digraphs': 'unicode',
        'Croatia - Use guillemets for quotes': 'alternatequotes',
    },
    'hu': {
        'Hungary': '',
        'Hungary - 101/qwerty/comma/Dead keys': '101_qwerty_comma_dead',
        'Hungary - 101/qwerty/comma/Eliminate dead keys': '101_qwerty_comma_nodead',
        'Hungary - 101/qwerty/dot/Dead keys': '101_qwerty_dot_dead',
        'Hungary - 101/qwerty/dot/Eliminate dead keys': '101_qwerty_dot_nodead',
        'Hungary - 101/qwertz/comma/Dead keys': '101_qwertz_comma_dead',
        'Hungary - 101/qwertz/comma/Eliminate dead keys': '101_qwertz_comma_nodead',
        'Hungary - 101/qwertz/dot/Dead keys': '101_qwertz_dot_dead',
        'Hungary - 101/qwertz/dot/Eliminate dead keys': '101_qwertz_dot_nodead',
        'Hungary - 102/qwerty/comma/Dead keys': '102_qwerty_comma_dead',
        'Hungary - 102/qwerty/comma/Eliminate dead keys': '102_qwerty_comma_nodead',
        'Hungary - 102/qwerty/dot/Dead keys': '102_qwerty_dot_dead',
        'Hungary - 102/qwerty/dot/Eliminate dead keys': '102_qwerty_dot_nodead',
        'Hungary - 102/qwertz/comma/Dead keys': '102_qwertz_comma_dead',
        'Hungary - 102/qwertz/comma/Eliminate dead keys': '102_qwertz_comma_nodead',
        'Hungary - 102/qwertz/dot/Dead keys': '102_qwertz_dot_dead',
        'Hungary - 102/qwertz/dot/Eliminate dead keys': '102_qwertz_dot_nodead',
        'Hungary - Eliminate dead keys': 'nodeadkeys',
        'Hungary - Standard': 'standard',
        'Hungary - qwerty': 'qwerty',
    },
    'ie': {
        'Ireland': '',
        'Ireland - CloGaelach': 'CloGaelach',
        'Ireland - Ogham': 'ogam',
        'Ireland - Ogham IS434': 'ogam_is434',
        'Ireland - UnicodeExpert': 'UnicodeExpert',
    },
    'il': {
        'Israel': '',
        'Israel - Biblical Hebrew (Tiro)': 'biblical',
        'Israel - Phonetic': 'phonetic',
        'Israel - lyx': 'lyx',
    },
    'in': {
        'India': '',
        'India - Bengali': 'ben',
        'India - Bengali Probhat': 'ben_probhat',
        'India - Gujarati': 'guj',
        'India - Gurmukhi': 'guru',
        'India - Gurmukhi Jhelum': 'jhelum',
        'India - Hindi Bolnagri': 'bolnagri',
        'India - Hindi Wx': 'hin-wx',
        'India - Kannada': 'kan',
        'India - Malayalam': 'mal',
        'India - Malayalam Lalitha': 'mal_lalitha',
        'India - Oriya': 'ori',
        'India - Tamil': 'tam',
        'India - Tamil TAB Typewriter': 'tam_TAB',
        'India - Tamil TSCII Typewriter': 'tam_TSCII',
        'India - Tamil Unicode': 'tam_unicode',
        'India - Telugu': 'tel',
        'India - Urdu, Alternative phonetic': 'urd-phonetic3',
        'India - Urdu, Phonetic': 'urd-phonetic',
        'India - Urdu, Winkeys': 'urd-winkeys',
    },
    'iq': {
        'Iraq': '',
        'Iraq - Kurdish, (F)': 'ku_f',
        'Iraq - Kurdish, Arabic-Latin': 'ku_ara',
        'Iraq - Kurdish, Latin Alt-Q': 'ku_alt',
        'Iraq - Kurdish, Latin Q': 'ku',
    },
    'ir': {
        'Iran': '',
        'Iran - Keypad': 'keypad',
        'Iran - Kurdish, (F)': 'ku_f',
        'Iran - Kurdish, Arabic-Latin': 'ku_ara',
        'Iran - Kurdish, Latin Alt-Q': 'ku_alt',
        'Iran - Kurdish, Latin Q': 'ku',
        'Iran - Pro': 'pro',
        'Iran - Pro Keypad': 'pro_keypad',
    },
    'is': {
        'Iceland': '',
        'Iceland - Dvorak': 'dvorak',
        'Iceland - Eliminate dead keys': 'nodeadkeys',
        'Iceland - Macintosh': 'mac',
        'Iceland - Sun dead keys': 'Sundeadkeys',
    },
    'it': {
        'Italy': '',
        'Italy - Eliminate dead keys': 'nodeadkeys',
        'Italy - Georgian': 'geo',
        'Italy - Macintosh': 'mac',
    },
    'jp': {
        'Japan': '',
        'Japan - Kana': 'kana',
        'Japan - OADG 109A': 'OADG109A',
    },
    'kg': {
        'Kyrgyzstan': '',
        'Kyrgyzstan - Phonetic': 'phonetic',
    },
    'kr': {
        'Korea, Republic of': '',
        'Korea, Republic of - 101/104 key Compatible': 'kr104',
    },
    'kz': {
        'Kazakhstan': '',
        'Kazakhstan - Kazakh with Russian': 'kazrus',
        'Kazakhstan - Russian with Kazakh': 'ruskaz',
    },
    'latam': {
        'Latin American': '',
        'Latin American - Eliminate dead keys': 'nodeadkeys',
        'Latin American - Include dead tilde': 'deadtilde',
        'Latin American - Sun dead keys': 'sundeadkeys',
    },
    'lk': {
        'Sri Lanka': '',
        'Sri Lanka - Tamil TAB Typewriter': 'tam_TAB',
        'Sri Lanka - Tamil Unicode': 'tam_unicode',
    },
    'lt': {
        'Lithuania': '',
        'Lithuania - IBM (LST 1205-92)': 'ibm',
        'Lithuania - LEKP': 'lekp',
        'Lithuania - LEKPa': 'lekpa',
        'Lithuania - Standard': 'std',
        'Lithuania - US keyboard with Lithuanian letters': 'us',
    },
    'lv': {
        'Latvia': '',
        'Latvia - Apostrophe () variant': 'apostrophe',
        'Latvia - F-letter (F) variant': 'fkey',
        'Latvia - Tilde (~) variant': 'tilde',
    },
    'ma': {
        'Morocco': '',
        'Morocco - French': 'french',
        'Morocco - Tifinagh': 'tifinagh',
        'Morocco - Tifinagh Alternative': 'tifinagh-alt',
        'Morocco - Tifinagh Alternative Phonetic': 'tifinagh-alt-phonetic',
        'Morocco - Tifinagh Extended': 'tifinagh-extended',
        'Morocco - Tifinagh Extended Phonetic': 'tifinagh-extended-phonetic',
        'Morocco - Tifinagh Phonetic': 'tifinagh-phonetic',
    },
    'me': {
        'Montenegro': '',
        'Montenegro - Cyrillic': 'cyrillic',
        'Montenegro - Cyrillic with guillemets': 'cyrillicalternatequotes',
        'Montenegro - Cyrillic, Z and ZHE swapped': 'cyrillicyz',
        'Montenegro - Latin qwerty': 'latinyz',
        'Montenegro - Latin unicode': 'latinunicode',
        'Montenegro - Latin unicode qwerty': 'latinunicodeyz',
        'Montenegro - Latin with guillemets': 'latinalternatequotes',
    },
    'mk': {
        'Macedonia': '',
        'Macedonia - Eliminate dead keys': 'nodeadkeys',
    },
    'mt': {
        'Malta': '',
        'Malta - Maltese keyboard with US layout': 'us',
    },
    'ng': {
        'Nigeria': '',
        'Nigeria - Hausa': 'hausa',
        'Nigeria - Igbo': 'igbo',
        'Nigeria - Yoruba': 'yoruba',
    },
    'nl': {
        'Netherlands': '',
        'Netherlands - Macintosh': 'mac',
        'Netherlands - Standard': 'std',
        'Netherlands - Sun dead keys': 'sundeadkeys',
    },
    'no': {
        'Norway': '',
        'Norway - Dvorak': 'dvorak',
        'Norway - Eliminate dead keys': 'nodeadkeys',
        'Norway - Macintosh': 'mac',
        'Norway - Macintosh, eliminate dead keys': 'mac_nodeadkeys',
        'Norway - Northern Saami': 'smi',
        'Norway - Northern Saami, eliminate dead keys': 'smi_nodeadkeys',
    },
    'pk': {
        'Pakistan': '',
        'Pakistan - Arabic': 'ara',
        'Pakistan - CRULP': 'urd-crulp',
        'Pakistan - NLA': 'urd-nla',
    },
    'pl': {
        'Poland': '',
        'Poland - Dvorak': 'dvorak',
        'Poland - Dvorak, Polish quotes on key "1/!"': 'dvorak_altquotes',
        'Poland - Dvorak, Polish quotes on quotemark key': 'dvorak_quotes',
        'Poland - Kashubian': 'csb',
        'Poland - Russian phonetic Dvorak': 'ru_phonetic_dvorak',
        'Poland - qwertz': 'qwertz',
    },
    'pt': {
        'Portugal': '',
        'Portugal - Eliminate dead keys': 'nodeadkeys',
        'Portugal - Macintosh': 'mac',
        'Portugal - Macintosh, Sun dead keys': 'mac_sundeadkeys',
        'Portugal - Macintosh, eliminate dead keys': 'mac_nodeadkeys',
        'Portugal - Nativo': 'nativo',
        'Portugal - Nativo for Esperanto': 'nativo-epo',
        'Portugal - Nativo for USA keyboards': 'nativo-us',
        'Portugal - Sun dead keys': 'sundeadkeys',
    },
    'ro': {
        'Romania': '',
        'Romania - Cedilla': 'cedilla',
        'Romania - Crimean Tatar (Dobruca-1 Q)': 'crh_dobruca1',
        'Romania - Crimean Tatar (Dobruca-2 Q)': 'crh_dobruca2',
        'Romania - Crimean Tatar (Turkish Alt-Q)': 'crh_alt',
        'Romania - Crimean Tatar (Turkish F)': 'crh_f',
        'Romania - Standard': 'std',
        'Romania - Standard (Cedilla)': 'std_cedilla',
        'Romania - Winkeys': 'winkeys',
    },
    'rs': {
        'Serbia': '',
        'Serbia - Latin': 'latin',
        'Serbia - Latin Unicode': 'latinunicode',
        'Serbia - Latin Unicode qwerty': 'latinunicodeyz',
        'Serbia - Latin qwerty': 'latinyz',
        'Serbia - Latin with guillemets': 'latinalternatequotes',
        'Serbia - With guillemets': 'alternatequotes',
        'Serbia - Z and ZHE swapped': 'yz',
    },
    'ru': {
        'Russia': '',
        'Russia - Chuvash': 'cv',
        'Russia - Chuvash Latin': 'cv_latin',
        'Russia - Kalmyk': 'xal',
        'Russia - Komi': 'kom',
        'Russia - Legacy': 'legacy',
        'Russia - Ossetian, Winkeys': 'os_winkeys',
        'Russia - Ossetian, legacy': 'os_legacy',
        'Russia - Phonetic': 'phonetic',
        'Russia - Tatar': 'tt',
        'Russia - Typewriter': 'typewriter',
        'Russia - Udmurt': 'udm',
        'Russia - Yakut': 'sah',
    },
    'se': {
        'Sweden': '',
        'Sweden - Dvorak': 'dvorak',
        'Sweden - Eliminate dead keys': 'nodeadkeys',
        'Sweden - Macintosh': 'mac',
        'Sweden - Northern Saami': 'smi',
        'Sweden - Russian phonetic': 'rus',
        'Sweden - Russian phonetic, eliminate dead keys': 'rus_nodeadkeys',
        'Sweden - Svdvorak': 'svdvorak',
    },
    'si': {
        'Slovenia': '',
        'Slovenia - US keyboard with Slovenian letters': 'us',
        'Slovenia - Use guillemets for quotes': 'alternatequotes',
    },
    'sk': {
        'Slovakia': '',
        'Slovakia - Extended Backslash': 'bksl',
        'Slovakia - qwerty': 'qwerty',
        'Slovakia - qwerty, extended Backslash': 'qwerty_bksl',
    },
    'sy': {
        'Syria': '',
        'Syria - Kurdish, (F)': 'ku_f',
        'Syria - Kurdish, Latin Alt-Q': 'ku_alt',
        'Syria - Kurdish, Latin Q': 'ku',
        'Syria - Syriac': 'syc',
        'Syria - Syriac phonetic': 'syc_phonetic',
    },
    'th': {
        'Thailand': '',
        'Thailand - Pattachote': 'pat',
        'Thailand - TIS-820.2538': 'tis',
    },
    'tj': {
        'Tajikistan': '',
        'Tajikistan - Legacy': 'legacy',
    },
    'tr': {
        'Turkey': '',
        'Turkey - (F)': 'f',
        'Turkey - Alt-Q': 'alt',
        'Turkey - Crimean Tatar (Turkish Alt-Q)': 'crh_alt',
        'Turkey - Crimean Tatar (Turkish F)': 'crh_f',
        'Turkey - Crimean Tatar (Turkish Q)': 'crh',
        'Turkey - International (with dead keys)': 'intl',
        'Turkey - Kurdish, (F)': 'ku_f',
        'Turkey - Kurdish, Latin Alt-Q': 'ku_alt',
        'Turkey - Kurdish, Latin Q': 'ku',
        'Turkey - Sun dead keys': 'sundeadkeys',
    },
    'ua': {
        'Ukraine': '',
        'Ukraine - Crimean Tatar (Turkish Alt-Q)': 'crh_alt',
        'Ukraine - Crimean Tatar (Turkish F)': 'crh_f',
        'Ukraine - Crimean Tatar (Turkish Q)': 'crh',
        'Ukraine - Homophonic': 'homophonic',
        'Ukraine - Phonetic': 'phonetic',
        'Ukraine - Standard RSTU': 'rstu',
        'Ukraine - Standard RSTU on Russian layout': 'rstu_ru',
        'Ukraine - Typewriter': 'typewriter',
        'Ukraine - Unicode': 'unicode',
        'Ukraine - Winkeys': 'winkeys',
    },
    'us': {
        'USA': '',
        'USA - Alternative international (former us_intl)': 'alt-intl',
        'USA - Cherokee': 'chr',
        'USA - Classic Dvorak': 'dvorak-classic',
        'USA - Colemak': 'colemak',
        'USA - Dvorak': 'dvorak',
        'USA - Dvorak international': 'dvorak-intl',
        'USA - Group toggle on multiply/divide key': 'olpc2',
        'USA - International (AltGr dead keys)': 'altgr-intl',
        'USA - International (with dead keys)': 'intl',
        'USA - Left handed Dvorak': 'dvorak-l',
        'USA - Macintosh': 'mac',
        'USA - Programmer Dvorak': 'dvp',
        'USA - Right handed Dvorak': 'dvorak-r',
        'USA - Russian phonetic': 'rus',
        'USA - With EuroSign on 5': 'euro',
    },
    'uz': {
        'Uzbekistan': '',
        'Uzbekistan - Crimean Tatar (Turkish Alt-Q)': 'crh_alt',
        'Uzbekistan - Crimean Tatar (Turkish F)': 'crh_f',
        'Uzbekistan - Crimean Tatar (Turkish Q)': 'crh',
        'Uzbekistan - Latin': 'latin',
    },
}

variants_rev = {}
for layoutname in variants.keys():
    variants_rev[layoutname] = {}
    variants_rev[layoutname].update(((v, k) for (k, v) in variants_rev[layoutname].iteritems()))
