#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/modprobe.d/araneo-launcher-theme" ]; then
		if [ "`md5sum \"/etc/modprobe.d/araneo-launcher-theme\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' araneo-launcher-theme | sed -n -e \"\\\\' /etc/modprobe.d/araneo-launcher-theme's/.* //p\"`" ]
		then
			rm -f "/etc/modprobe.d/araneo-launcher-theme"
		fi
	fi
fi
# End automatically added section
