#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd avahi-autoipd >/dev/null; then
      adduser --disabled-password --quiet --system \
        --home /var/lib/avahi-autoipd \
        --gecos "Avahi autoip daemon" --group avahi-autoipd
    fi
    # FIXME: restart it somehow... SIGHUP?
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac



