#! /bin/sh -e

. /usr/share/debconf/confmodule
. /usr/share/checkbox/install/postinst

# Automatically added by dh_pycentral
rm -f /var/lib/pycentral/checkbox.pkgremove
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall checkbox
	if grep -qs '^checkbox$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^checkbox$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section

