#! /bin/sh -e

. /usr/share/debconf/confmodule
. /usr/share/checkbox/install/postinst

# Automatically added by dh_pycentral
rm -f /var/lib/pycentral/checkbox-gtk.pkgremove
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall checkbox-gtk
	if grep -qs '^checkbox-gtk$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^checkbox-gtk$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section

