#!/bin/sh

set -e

case "$1" in
       configure|abort-upgrade|abort-remove|abort-deconfigure)
               #
               #       Install the info documentation
               #
	       install-info --section "General commands" "General commands" \
			    --quiet /usr/share/info/ed.info.gz
	       update-alternatives --quiet --install /usr/bin/editor editor /bin/ed -100 \
		  --slave /usr/share/man/man1/editor.1.gz editor.1.gz /usr/share/man/man1/ed.1.gz
               ;;
esac
