#! /bin/sh
set -e

# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/HighContrastLargePrintInverse
fi
# End automatically added section


rm -f /usr/share/icons/icon-theme.cache
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    for theme in $(dpkg -L gnome-accessibility-themes | sed -n 's#^/usr/share/icons/\([^/]*\)/.*#\1#p' | uniq); do
        gtk-update-icon-cache /usr/share/icons/$theme
    done
fi
