#!/bin/sh
set -e
# Automatically added by dh_gconf
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
	gconf-schemas --unregister drivemount.schemas charpick.schemas cpufreq-applet.schemas stickynotes.schemas geyes.schemas multiload.schemas mixer.schemas 
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  gnome-applets-data
fi
# End automatically added section
