#!/bin/sh
set -e
# Automatically added by dh_gconf
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
	gconf-schemas --unregister apps_gnome_settings_daemon_screensaver.schemas desktop_gnome_font_rendering.schemas apps_gnome_settings_daemon_xrandr.schemas gnome-settings-daemon.schemas apps_gnome_settings_daemon_keybindings.schemas desktop_gnome_keybindings.schemas 
fi
# End automatically added section
