#!/bin/sh
set -e

ua_remove () {
	update-alternatives \
        --remove xinput-$1 \
        /etc/X11/xinit/xinput.d/$2 ;
}

case "$1" in
    remove|upgrade|deconfigure)
        # remove defaults
        ua_remove all_ALL default
        ua_remove all_ALL default-xim
        # remove nones
        ua_remove all_ALL none
        ua_remove th_TH th-xim
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
