#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/modprobe.d/iptables" ]; then
		if [ "`md5sum \"/etc/modprobe.d/iptables\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' iptables | sed -n -e \"\\\\' /etc/modprobe.d/iptables's/.* //p\"`" ]
		then
			rm -f "/etc/modprobe.d/iptables"
		fi
	fi
fi
# End automatically added section
