#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/modprobe.d/liblircclient0" ]; then
		if [ "`md5sum \"/etc/modprobe.d/liblircclient0\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' liblircclient0 | sed -n -e \"\\\\' /etc/modprobe.d/liblircclient0's/.* //p\"`" ]
		then
			rm -f "/etc/modprobe.d/liblircclient0"
		fi
	fi
fi
# End automatically added section
