#!/bin/sh
set -e
# Automatically added by dh_pycentral
rm -f /var/lib/pycentral/python-software-properties.pkgremove
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall python-software-properties
	if grep -qs '^python-software-properties$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^python-software-properties$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section
