#!/bin/sh
set -e
# Automatically added by dh_pycentral
rm -f /var/lib/pycentral/python-launchpad-integration.pkgremove
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall python-launchpad-integration
	if grep -qs '^python-launchpad-integration$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^python-launchpad-integration$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section
