#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/modprobe.d/spider-usb-power-save" ]; then
		if [ "`md5sum \"/etc/modprobe.d/spider-usb-power-save\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' spider-usb-power-save | sed -n -e \"\\\\' /etc/modprobe.d/spider-usb-power-save's/.* //p\"`" ]
		then
			rm -f "/etc/modprobe.d/spider-usb-power-save"
		fi
	fi
fi
# End automatically added section
