#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e "/etc/modprobe.d/spider-utils" ]; then
		echo "Preserving user changes to /etc/modprobe.d/spider-utils.conf ..."
		if [ -e "/etc/modprobe.d/spider-utils.conf" ]; then
			mv -f "/etc/modprobe.d/spider-utils.conf" "/etc/modprobe.d/spider-utils.conf.dpkg-new"
		fi
		mv -f "/etc/modprobe.d/spider-utils" "/etc/modprobe.d/spider-utils.conf"
	fi
fi
# End automatically added section
