#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/modprobe.d/spider-version" ]; then
		if [ "`md5sum \"/etc/modprobe.d/spider-version\" | sed -e \"s/ .*//\"`" = \
		     "`dpkg-query -W -f='${Conffiles}' spider-version | sed -n -e \"\\\\' /etc/modprobe.d/spider-version's/.* //p\"`" ]
		then
			rm -f "/etc/modprobe.d/spider-version"
		fi
	fi
fi
# End automatically added section
