#!/bin/sh

STAMP=/var/lib/update-notifier/dpkg-run-stamp

if [ "$1" = purge -a -f $STAMP ]; then
	rm $STAMP
fi

# Automatically added by dh_gconf
if [ "$1" = purge ]; then
	OLD_DIR=/etc/gconf/schemas
	SCHEMA_FILES="update-notifier.schemas "
	if [ -d $OLD_DIR ]; then
		for SCHEMA in $SCHEMA_FILES; do
			rm -f $OLD_DIR/$SCHEMA
		done
		rmdir -p --ignore-fail-on-non-empty $OLD_DIR
	fi
fi
# End automatically added section

