#!/bin/bash
# $Id: bug.script 2906 2007-05-29 11:01:20Z frank $
set -e

cat <<EOF

Please read and follow the instructions in the first lines below
the text: "-- Package-specific info:".
Thank you.

Press ENTER to continue
EOF

getkey

cat >&3 <<EOF
If you report an error when running one of the TeX-related binaries 
(latex, pdftex, metafont,...), or if the bug is related to bad or wrong
output, please include a MINIMAL example input file that produces the
error in your report. Don't forget to also include minimal examples of
other files that are needed, e.g. bibtex databases. Often it also helps
to include the logfile. Please, never send included pictures!

If your example file isn't short or produces more than one page of
output (except when multiple pages are needed to show the problem),
you can probably minimize it further. Instructions on how to do that
can be found at

http://www.latex-einfuehrung.de/mini-en.html (english)

or 

http://www.latex-einfuehrung.de/mini.html (german)

##################################
minimal input file


##################################
other files

EOF

# unset error exit since those files might not be present...
set +e
for dir in $(kpsexpand '$TEXMF' | sed -e 's/,/ /g;s/[!{}]//g;'); do
  ls_R_files="$ls_R_files $(ls $dir/ls-R 2>/dev/null)";
done
ls_R_files="$ls_R_files $(ls /usr/share/texmf-texlive/ls-R 2>/dev/null)"

echo "######################################" >&3
echo " List of ls-R files" >&3
echo >&3
for file in $ls_R_files; do
  ls -l $file >&3
#  echo >&3
#  cat $file >&3
#  echo "######################################" >&3
done

echo "######################################" >&3
echo " Config files" >&3
for i in texmf.cnf fmtutil.cnf updmap.cfg ; do
  f=$(kpsewhich --format='web2c files' $i)
  if [ -z "$f" ] ; then
    echo "Warning: $i cannot be found with kpsewhich!" >&3
  else
    ls -l $f >&3
  fi
done
for i in language.dat ; do
  f=$(kpsewhich -progname=latex $i)
  if [ -z "$f" ] ; then
    echo "Warning: $i cannot be found with kpsewhich!" >&3
  else
    ls -l $f >&3
  fi
done

echo "######################################" >&3
echo " Files in /etc/texmf/web2c/" >&3
ls -l /etc/texmf/web2c/ >&3

echo "######################################" >&3
echo " md5sums of texmf.d" >&3
md5sum /etc/texmf/texmf.d/* >&3

