#!/bin/sh

. /usr/share/recovery-mode/l10n.sh

if [ "$1" = "test" ]; then
  echo $(eval_gettext "Update grub bootloader")
  exit 0
fi

# FIXME: add this too? how to find out boot device?
#        add menu to ask?
#grub-install
update-grub

exit 0
