#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from kde/ProgressDialog.ui on Wed Jul 15 15:57:06 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_progress_dialog(object):
    def setupUi(self, progress_dialog):
        progress_dialog.setObjectName("progress_dialog")
        progress_dialog.resize(335, 124)
        progress_dialog.setSizeGripEnabled(False)
        self.vboxlayout = QtGui.QVBoxLayout(progress_dialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.description = QtGui.QLabel(progress_dialog)
        self.description.setWordWrap(False)
        self.description.setObjectName("description")
        self.vboxlayout1.addWidget(self.description)
        self.vboxlayout.addLayout(self.vboxlayout1)
        self.progressBar = QtGui.QProgressBar(progress_dialog)
        self.progressBar.setProperty("value", QtCore.QVariant(24))
        self.progressBar.setObjectName("progressBar")
        self.vboxlayout.addWidget(self.progressBar)
        spacerItem = QtGui.QSpacerItem(21, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.buttonCancel = QtGui.QPushButton(progress_dialog)
        self.buttonCancel.setAutoDefault(True)
        self.buttonCancel.setObjectName("buttonCancel")
        self.hboxlayout.addWidget(self.buttonCancel)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(progress_dialog)
        QtCore.QObject.connect(self.buttonCancel, QtCore.SIGNAL("clicked()"), progress_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(progress_dialog)

    def retranslateUi(self, progress_dialog):
        self.description.setText(kdecore.i18n("label"))
        self.buttonCancel.setText(kdecore.i18n("&Cancel"))

