#!/bin/sh

# TODO: This script is triggered by udev so it should not call sleep directly
sleep 15

/usr/sbin/usb_modeswitch -c /usr/share/usb-modeswitch/L-05A.conf > /tmp/usbswitch.log
/usr/sbin/usb_modeswitch -c /usr/share/usb-modeswitch/L-05A-2.conf >> /tmp/usbswitch.log
